### ISSUE TITLE
Nice links!

### ISSUE THREAD

**Issue by RattyDAVE** [FuzzyMainframes/Awesome-Mainframes#1]
No issues -- I saw you followed me.....

Love the links!

Worth adding this one...
http://simh.trailing-edge.com/software.html

**Comment by roblthegreat** [comment]
Thanks, RattyDAVE. I appreciate the link and have used the simh VAX simulator for years.  I hadn't considered it for inclusion as this list is targeting primarily the IBM System/360 & System/370-era. 

I had forgotten that simh also includes emulators for some of the older mainframes such as IBM 1401, 1620, 7090/7094, System 3.  I may end up adding a section for those machines and will add the link.

**Comment by roblthegreat** [comment]
RattyDAVE -- Done!  I have added the link for the SimH software kits and to SimH itself.  Thanks again.

**Comment by sccosel** [comment]
Great page of Links.  Here are some more:
https://webfiles.uci.edu/scosel/index.html
http://wotho.ethz.ch/mvt4apl-2.00/
https://groups.io/g/hercules-os380/files/_$OSTL37.5.pdf
http://mvs380.sourceforge.net/
https://curlie.org/Bookmarks/D/deepblue2/  (my notes of other websites I don't want to lose the URL! - Sadly, some no longer exist).
That's a bunch of links for now!

**Comment by roblthegreat** [comment]
@sccosel thank you for the submission.  I have created a separate issue #2 for your submission, since this issue was already closed.
